import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import HeroWithCards from "./HeroWithCards/page";
import Hero from "./Hero/page";
import Navbar from "./Navbar/page";
import PrivacySixCards from "./PrivacySixCards/page";
import ServicesLongPage from "./ServicesLongPage/page";
import Footer from "./Footer/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <Hero />
        <HeroWithCards />
        <PrivacySixCards />
        {children}
        <ServicesLongPage />
        <Footer />
      </body>
    </html>
  );
}
