import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Struggles from "./Struggles/page";
import Navbar from "../Navbar/page";
import Footer from "../Footer/page";
import BeginTherapyStrip from "./BeginTherapyStrip/page";
import Faq from "./Faq/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Navbar/>
        <Struggles />
        <BeginTherapyStrip />
        {/* {children} */}
        {/* <Faq /> */}
        <Footer />
      </body>
    </html>
  );
}
